### ISSUE TITLE
resourceGroupName allows 90 characters not 80

### ISSUE THREAD

**Issue by kiwidev** [Azure/azure-resource-manager-rpc#42]
I believe that the resourceGroupName allows 90 characters. This was changed previously inside the earlier version of this spec, but the change can't have migrated through to here (resource-api-reference.md)

**Comment by stan-sz** [comment]
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftresources

**Comment by kiwidev** [comment]
Issue closed as previously resolved.
